sudo: false
dist: trusty

language: node_js
node_js:
  - '6.11'

addons:
  chrome: stable

cache:
  directories:
      - node_modules

env:
  - API_URL=http://testurl

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm test
  - npm run e2e
  - npm run build:prod

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
