sudo: false
dist: trusty

language: node_js
node_js:
  - '6.11'

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm test
  - npm run e2e

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
