sudo: false
dist: trusty

language: node_js
node_js:
  - '6.11'

before_install:
  - export CHROME_BIN=chromium-browser

install:
  - npm install -g angular-cli
  - npm install

script:
  - xvfb-run -a ng test -- --single-run --no-progress --browser=ChromeNoSandbox
  - xvfb-run -a ng e2e -- --no-progress --config=protractor-ci.conf.js

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
