language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng test --watch false
  - ng e2e

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
