sudo: required
dist: trusty

language: node_js
node_js:
  - '6.11'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g angular-cli
  - npm install
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
  - xvfb-run -a ng test -- --single-run --no-progress --browser=ChromeNoSandbox
  - xvfb-run -a ng e2e -- --no-progress --config=protractor-ci.conf.js

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
