sudo: false
dist: trusty

language: node_js
node_js:
  - '6.11'

addons:
  chrome: stable

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm test
  - npm run e2e

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
